SORTIERUNGFILES = sortierung.c sortierungsvergleich.c stoppuhr.c zufallsarray.c

sortierungsvergleich:
	gcc -Wall -O0 -g -o sortierungsvergleich.out $(SORTIERUNGFILES)

clean:
	rm -rf sortierungsvergleich.out